In [ ]:
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 52.9 MB/s eta 0:00:00


In [ ]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=cd23bac90f9c2ba015047307b13f9368d535b5b7988131ff4622f3e2dac1663d
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget


In [ ]:
import gensim.downloader as api

model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [21]:
model['pen']

array([ 0.00149536,  0.06152344, -0.22460938, -0.00952148, -0.03466797,
       -0.00793457, -0.24511719,  0.07470703,  0.07910156,  0.00878906,
        0.00112915, -0.265625  , -0.13964844, -0.03222656, -0.14257812,
       -0.13378906,  0.0100708 ,  0.1953125 ,  0.01379395, -0.23925781,
        0.18457031, -0.03442383,  0.06103516, -0.18554688, -0.12792969,
       -0.125     ,  0.04907227, -0.07373047, -0.14648438,  0.09716797,
       -0.09082031,  0.12890625, -0.125     ,  0.28125   , -0.11621094,
        0.25585938, -0.12060547,  0.27929688,  0.14160156, -0.04052734,
        0.05175781, -0.06030273,  0.17871094, -0.0072937 ,  0.48632812,
        0.08398438,  0.17089844,  0.18066406, -0.04321289, -0.01660156,
       -0.46875   , -0.171875  ,  0.06396484, -0.31054688, -0.06152344,
       -0.125     ,  0.02624512, -0.27929688,  0.18554688, -0.09179688,
        0.0088501 , -0.09667969, -0.02770996, -0.18359375,  0.02624512,
       -0.18945312, -0.27734375,  0.23046875, -0.23339844,  0.22

In [22]:
model['Laptop']

array([-1.94335938e-01, -2.10937500e-01, -7.56835938e-02,  2.87109375e-01,
        6.29882812e-02,  6.32812500e-01,  5.07812500e-01,  1.39648438e-01,
        4.55078125e-01, -3.24707031e-02, -7.81250000e-02,  2.55859375e-01,
        4.00390625e-01, -6.14166260e-04,  5.59082031e-02, -1.08398438e-01,
        3.95507812e-02,  4.15039062e-02,  5.02929688e-02,  2.19726562e-02,
        3.41796875e-02, -1.23046875e-01,  3.41796875e-01,  3.20312500e-01,
       -2.29492188e-01,  2.20947266e-02,  1.67236328e-02,  2.12890625e-01,
        1.20117188e-01, -1.13769531e-01, -2.92968750e-01, -7.42187500e-02,
       -2.20703125e-01, -2.59765625e-01, -6.34765625e-02, -1.72851562e-01,
       -4.21875000e-01, -9.37500000e-02, -4.70703125e-01,  4.73632812e-02,
       -1.83593750e-01,  3.49609375e-01,  2.09960938e-02,  2.61718750e-01,
        7.37304688e-02, -2.02148438e-01, -1.86523438e-01,  9.61914062e-02,
        2.81250000e-01, -1.57226562e-01, -4.45312500e-01, -8.88671875e-02,
       -5.82885742e-03,  

In [23]:
model['notebook']

array([-1.70898438e-02,  1.54296875e-01, -7.91015625e-02, -1.26342773e-02,
        8.20312500e-02,  1.63574219e-02,  8.20312500e-02, -9.13085938e-02,
        4.37500000e-01, -3.69262695e-03, -2.12890625e-01,  6.00585938e-02,
        2.17773438e-01,  1.04980469e-01,  6.83593750e-02, -1.28906250e-01,
       -5.22460938e-02,  9.37500000e-02,  1.67968750e-01, -3.26171875e-01,
        2.12890625e-01, -4.44335938e-02, -1.73828125e-01, -1.96289062e-01,
       -9.91210938e-02, -6.68945312e-02, -1.51367188e-01,  1.63085938e-01,
        6.73828125e-02,  3.59375000e-01, -1.05590820e-02,  1.14257812e-01,
       -8.20312500e-02,  2.87109375e-01, -8.30078125e-02, -4.07714844e-02,
       -1.66992188e-01,  1.43554688e-01,  1.91650391e-02,  1.00585938e-01,
        2.62451172e-02,  2.18505859e-02,  1.59912109e-02,  1.26953125e-01,
        2.36328125e-01, -9.17968750e-02, -6.64062500e-02,  1.30859375e-01,
        2.08007812e-01, -4.78515625e-02, -2.55859375e-01, -1.32812500e-01,
       -1.77734375e-01,  

In [24]:
model.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [25]:
model.most_similar('computer')

[('computers', 0.7979379892349243),
 ('laptop', 0.6640493273735046),
 ('laptop_computer', 0.6548868417739868),
 ('Computer', 0.647333562374115),
 ('com_puter', 0.6082080006599426),
 ('technician_Leonard_Luchko', 0.5662748217582703),
 ('mainframes_minicomputers', 0.5617720484733582),
 ('laptop_computers', 0.5585449934005737),
 ('PC', 0.5539618730545044),
 ('maker_Dell_DELL.O', 0.5519254207611084)]

In [26]:
model.most_similar('mobile')

[('mobile_phones', 0.7054650187492371),
 ('Mobile', 0.6691667437553406),
 ('smartphone', 0.6600653529167175),
 ('smartphones', 0.6404396891593933),
 ('handsets', 0.640427827835083),
 ('handset', 0.6366176605224609),
 ('mobiles', 0.6357012987136841),
 ('Impoverished_NKorea_gets', 0.630828320980072),
 ('Jason_Fulmines_director', 0.6140599250793457),
 ('Cyfrowa_PTC', 0.6105130910873413)]

In [27]:
model.similarity('computer','laptop')

np.float32(0.66404927)

In [30]:
model.similarity('men','html')

np.float32(0.03469084)

In [31]:
model.doesnt_match(['PHP','java','monkey'])

'monkey'

In [32]:
model.doesnt_match(['PHP','java','python'])

'python'

In [33]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [34]:
vec = model['Messi'] - model['Football'] + model['Cricket']
model.most_similar([vec])

[('Messi', 0.7382575273513794),
 ('Sehwag', 0.6777455806732178),
 ('Tendulkar', 0.6748222708702087),
 ('Xavi', 0.6610832810401917),
 ('Dravid', 0.6569646596908569),
 ('Dhoni', 0.6550688743591309),
 ('Lionel_Messi', 0.6407608389854431),
 ('Forlan', 0.640610933303833),
 ('Yuvraj', 0.6390379667282104),
 ('Ponting', 0.6390198469161987)]

In [35]:
vec = model['Messi'] - model['Football'] + model['Hockey']
model.most_similar([vec])

[('Messi', 0.7521781921386719),
 ('Lionel_Messi', 0.6318718194961548),
 ('Iniesta', 0.6182227730751038),
 ('Ronaldinho', 0.607815682888031),
 ('Xavi', 0.6052352786064148),
 ('Forlan', 0.5919727683067322),
 ('Ibrahimovic', 0.5867048501968384),
 ('Higuain', 0.5844464302062988),
 ('Luis_Fabiano', 0.5822347402572632),
 ('Higuaín', 0.5799975991249084)]